package com.mycompany.projetoa3lojaderoupassociais;

public enum EnumPassoMenu {
    PASSO_INICIAL,
    PASSO_ADMINISTRADOR,
    PASSO_SUBMENU_FUNC,
    PASSO_SUBMENU_PROD,
    PASSO_VENDER_PRODUTO,
    PASSO_CADASTRAR_PRODUTO,
    PASSO_BUSCAR_PRODUTO,
    PASSO_LISTAR_PRODUTO,
    PASSO_EDITAR_PRODUTO,
    PASSO_REMOVER_PRODUTO,
    PASSO_EXIBIR_REGISTRO_VENDA_PRODUTO;
}
